## Notes:

old trans_ref is created from culmination of all transcripts and their metadata over time. <br>
There is a cell section at the bottom of the notebook in the transcript creation process that details how to add transript metadata.<br>
This notebook is intended to show how slide info is added to that, but I highly recommend to incorporate it into the slide process <br>
in a more natural way.

In [23]:
import pandas as pd

# import most recent version of trans_ref 
# remember to read and save trans_ref with a gzip compression to avoid github size limit issues
trans_ref_curr = pd.read_csv('./trans_ref.csv', compression='gzip')

# import most up to date version of df_slides_main
slides_ref = pd.read_csv('../slides/dropbox_slide_pipeline/data_ref/df_slides_main.csv')
# get only needed columns
slides_ref = slides_ref[['file_name', 'event_id', 'address', 'date']]
# rename for lack of confusion
slides_ref.rename(columns={'event_id': 'slide_id'}, inplace=True)
# concatenate to old trans_ref
new_ref = pd.concat([trans_ref_curr, slides_ref])
# drop duplicates
new_ref = new_ref.drop_duplicates()
# save file -- make sure this file gets uploaded to github and pushed to deployment
#new_ref.to_csv('./trans_ref.csv', index=False, compression='gzip')
new_ref

/var/folders/1l/pscgd43n4mg353g681xy7nj06fv5jx/T/ipykernel_50504/4169781360.py:5: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  trans_ref_curr = pd.read_csv('./trans_ref.csv', compression='gzip')

,report,transcript_source,file_name,date,slide_id,address
0,108.0,3.0,ciq_108,2006-05-15,NaN,NaN
1,109.0,3.0,ciq_109,2006-08-14,NaN,NaN
2,111.0,3.0,ciq_111,2007-02-15,NaN,NaN
3,112.0,3.0,ciq_112,2007-05-14,NaN,NaN
4,113.0,3.0,ciq_113,2007-08-14,NaN,NaN
...,...,...,...,...,...,...
2210806,NaN,NaN,"JOYY, Inc. Q2 2022 Earnings Call-20220829.pdf",2022-08-29,1.202350e+09,./UNKNOWN/2022
2210807,NaN,NaN,Zinc Media Group Plc Q2 2023 Earnings Call-202...,2023-09-28,1.202859e+09,./UNKNOWN/2023
2210808,NaN,NaN,Zanaga Iron Ore Co. Ltd. Slide 1: Investor Mee...,2023-11-06,1.202945e+09,./UNKNOWN/2023
2210809,NaN,NaN,Zardoya Otis SA Slide 1: Bernstein Strategic D...,2020-05-28,1.201717e+09,./UNKNOWN/2020
2210810,NaN,NaN,Zardoya Otis SA Slide 1: Barclays Conference-2...,2020-09-03,1.201717e+09,./UNKNOWN/2020

# Archive

In [ ]:
# This block details the addition of old slide collections completed by Sonali and Esfandiar in Q3 2023

# all old files from the slide process were download manually, and as such, are uploaded separately into a special folder at:
# /project/FactSet/Doc_Retrieval_API/factset_slides_API/output/OLD_SLIDE_DOWNLOADS

# these slides do not correspond to slide_IDs so can only be retrieved by firm_name string

# their file_names are not uniquely named so the unique identifer had to be manually created. 
# this is done by adding the firm_name (latter part of the folder_name) as a prefix to the 'file_name' column in trans_ref
# note that ACTUAL file names have not changed -- only how their names are represented on trans_ref

In [49]:
import os
import re

old_name_adds = []

#  collect names and addresses of all files in old_slide_downlaod such that they can be added to docgetter
for energy_util in os.listdir('../OLD_SLIDE_DOWNLOAD/'):
    if energy_util.startswith('.'):
        continue
    # get energy/utility folder prefix
    pre_prefix = energy_util
    for folder_name in os.listdir(f'../OLD_SLIDE_DOWNLOAD/{pre_prefix}'):
        if folder_name.startswith('.'):
            continue
        # get firm name -- remove number + underscore
        firm_name = folder_name.split('_')[-1]
        # standardize firm name by removing whitespace, adding underscore etc.
        firm_name = re.sub('\s', '_', firm_name)
        for f_name in os.listdir(f'../OLD_SLIDE_DOWNLOAD/{pre_prefix}/{folder_name}'):
            if f_name.startswith('.'):
                continue
            #file_name = firm_name + '_' + f_name
            address = f'./OLD_SLIDE_DOWNLOAD/{pre_prefix}/{folder_name}'
            old_name_adds.append([f_name, address])


df = pd.DataFrame(old_name_adds, columns=['file_name', 'address'])
print(df.shape)
df.sample(5)

(6804, 2)

,file_name,address
1382,Newbuilds Update June 2021.pdf,./OLD_SLIDE_DOWNLOAD/Energy/44_TRANSOCEAN LTD
3439,fy2020-eng_presentation-h.pdf,./OLD_SLIDE_DOWNLOAD/Utilities/54_PPC
1171,PSX-2Q-23-ER-Earnings-Release-Presentation.pdf,./OLD_SLIDE_DOWNLOAD/Energy/14_PHILLIPS 66
5298,SO-2022-Q2-Earnings-Call-FINAL.pdf,./OLD_SLIDE_DOWNLOAD/Utilities/18_SOUTHERN CO
4085,June-2019-Investor-Presentation.pdf,./OLD_SLIDE_DOWNLOAD/Utilities/98_EMERA

In [59]:
df[~df.file_name.duplicated(keep=False)].sort_values('file_name')

,file_name,address
2472,008-The-Lower-Slochteren-Play-Marloes-Jongeriu...,./OLD_SLIDE_DOWNLOAD/Energy/54_ENERGIE BEHEER ...
189,00n_s_speech011116.pdf,./OLD_SLIDE_DOWNLOAD/Energy/34_IMPERIAL OIL LTD
186,00n_s_speech011215.pdf,./OLD_SLIDE_DOWNLOAD/Energy/34_IMPERIAL OIL LTD
197,00n_s_speech011817.pdf,./OLD_SLIDE_DOWNLOAD/Energy/34_IMPERIAL OIL LTD
196,00n_s_speech092116.pdf,./OLD_SLIDE_DOWNLOAD/Energy/34_IMPERIAL OIL LTD
...,...,...
3275,Î—ELPE_Results_Presentation-2Q_2021.pdf,./OLD_SLIDE_DOWNLOAD/Energy/80_HELLENIQ ENERGY...
3256,Î—ELPE_Results_Presentation-3Q_2020.pdf,./OLD_SLIDE_DOWNLOAD/Energy/80_HELLENIQ ENERGY...
3254,Î—ELPE_Results_Presentation-3Q_2021_20vF.pdf,./OLD_SLIDE_DOWNLOAD/Energy/80_HELLENIQ ENERGY...
3263,Î—ELPE_Results_Presentation-4Q_2021.pdf,./OLD_SLIDE_DOWNLOAD/Energy/80_HELLENIQ ENERGY...
3252,Î—ELPE_Results_Presentation_2Q22..pdf,./OLD_SLIDE_DOWNLOAD/Energy/80_HELLENIQ ENERGY...

In [54]:
# concat these rows to trans_ref
new_ref = pd.concat([new_ref, df])
new_ref

,report,transcript_source,file_name,date,slide_id,address
0,108.0,3.0,ciq_108,2006-05-15,NaN,NaN
1,109.0,3.0,ciq_109,2006-08-14,NaN,NaN
2,111.0,3.0,ciq_111,2007-02-15,NaN,NaN
3,112.0,3.0,ciq_112,2007-05-14,NaN,NaN
4,113.0,3.0,ciq_113,2007-08-14,NaN,NaN
...,...,...,...,...,...,...
6799,NaN,NaN,alpiq_presentation_analyst_call_2018_en.pdf,NaN,NaN,./OLD_SLIDE_DOWNLOAD/Utilities/41_ALPIQ
6800,NaN,NaN,alpiq_presentation_financial_analyst_conferenc...,NaN,NaN,./OLD_SLIDE_DOWNLOAD/Utilities/41_ALPIQ
6801,NaN,NaN,alpiq_hy_results_presentation_2018_en.pdf,NaN,NaN,./OLD_SLIDE_DOWNLOAD/Utilities/41_ALPIQ
6802,NaN,NaN,alpiq_presentation_financial_analyst_conferenc...,NaN,NaN,./OLD_SLIDE_DOWNLOAD/Utilities/41_ALPIQ
6803,NaN,NaN,alpiq_presentation_annual_media_conference_202...,NaN,NaN,./OLD_SLIDE_DOWNLOAD/Utilities/41_ALPIQ

In [ ]:
new_ref.to_csv('./trans_ref.csv', index=False, compression='gzip')